//! Task payload definition for distributed compute jobs.
//!
//! This module defines the [`Task`] struct that is sent from one Sangam node
//! to another when delegating a unit of work, along with the [`TaskType`]
//! enum that enumerates all computations the runtime currently supports.
//! Both types are serialized to JSON and transmitted inside a
//! [`crate::models::message::MessageType::Task`] envelope.

use serde::{Deserialize, Serialize};

/// The kind of computation a [`Task`] requests the remote worker to perform.
///
/// Each variant maps to a specific algorithm implemented in
/// [`crate::tasks::executor`]. New compute primitives are added by extending
/// this enum and adding a corresponding execution branch in the executor.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub enum TaskType {
    /// Sum all integers in [`Task::numbers`] and return the total.
    ///
    /// The result is placed in [`crate::tasks::result::TaskResult::result`]
    /// and the status is set to `"completed"` on success.
    Sum,
}

/// A unit of distributed work sent from one Sangam node to another.
///
/// The originating node constructs a `Task`, wraps it in a
/// [`crate::models::message::NodeMessage`], and delivers it to a remote peer
/// over TCP. The peer's executor processes the task and returns a
/// [`crate::tasks::result::TaskResult`] with the same `task_id`.
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
pub struct Task {
    /// Globally unique identifier for this task instance.
    ///
    /// Generated by the originating node (typically a UUID v4) and echoed
    /// back in the corresponding [`crate::tasks::result::TaskResult`] so the
    /// caller can match results to outstanding requests.
    pub task_id: String,

    /// The computation this task requests the remote worker to perform.
    ///
    /// Determines which execution branch in
    /// [`crate::tasks::executor`] is invoked.
    pub task_type: TaskType,

    /// The input integers the worker should operate on.
    ///
    /// For [`TaskType::Sum`], all elements of this slice are summed and the
    /// total is returned in the result payload.
    pub numbers: Vec<i32>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn task_roundtrips_through_json() {
        let task = Task {
            task_id: "abc-123".to_string(),
            task_type: TaskType::Sum,
            numbers: vec![1, 2, 3],
        };
        let json = serde_json::to_string(&task).expect("serialize");
        let back: Task = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(task, back);
    }
}
